name: CD
on:
  push:
    branches:
      - '*'
jobs:
  Buid-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: 1.10.2 # Define the elixir version [required]
          otp-version: 22.2 # Define the OTP version [required]
      # - name: Cache mix modules
      #   uses: actions/cache@v1
      #   env:
      #     cache-name: cache-mix-modules
      #   with:
      #     path: deps
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      - name: Install Elixir Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only prod
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      # - name: Cache npm modules
      #   uses: actions/cache@v1
      #   env:
      #     cache-name: cache-npm-modules
      #   with:
      #     path: assets/node_module
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      - name: Install Npm Dependencies
        working-directory: ./assets
        run: npm install
      - name: Compile elixir
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
        run: MIX_ENV=prod mix compile
      - name: Compile assets
        run: |
          npm run deploy --prefix ./assets
          mix phx.digest
      - name: Build Mix Release
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: MIX_ENV=prod mix release --version ${{ github.sha }}
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "_build/prod/prod-${{ github.sha }}.tar.gz"
          target: "/tmp"
          debug: true
      - name: Extract release command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p elixir_group
            mkdir -p elixir_group/releases
            mkdir -p elixir_group/releases/${{ github.sha }}
            tar -xzvf /tmp/_build/prod/prod-${{ github.sha }}.tar.gz --directory ~/elixir_group/releases/${{ github.sha}}/
            ./elixir_group/elixir_group stop
            ln -sfT ~/elixir_group/releases/${{ github.sha}}/ ~/elixir_group/current
            ./elixir_group/elixir_group start
      - name: Run migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ./elixir_group/current/bin/prod eval "ElixirGroup.Release.migrate"
